### ISSUE TITLE
Missing license definition

### ISSUE THREAD

**Issue by swrh** [alirezaomidi/SuperMario-Allegro-Cpp#1]
First I'd like to congratulate the author for writing such a nice game prototype in C++. Very well structured, clean and using very straight forward code. Quite easy to understand/read, too.

I'd like to know if I can use it as a reference for C++ programming lessons I'm willing to teach. It would be used for educational purposes only, but some of my students might want to develop the game even further and to do that it would be nice if there was a license defined. Is there any? If not, could you please update the README file or upload the LICENSE file?

Thanks in advance.

**Comment by alirezaomidi** [comment]
Thanks for your attention to the project.
I just updated the README and added the LICENSE file. The game is licensed under MIT. eb9ade8101e586f7824a8f6fa06419264b6ead1b

Keep in mind that the game has some bugs which I couldn't spend time on fixing them. It would be helpful if you or your students fix them so there will be a bug free game which is more appropriate to teach/learn. 

Hope you find the code helpful.
